version: '3.9'

services:
  db:
    image: postgres:15
    container_name: email_pg
    restart: always
    environment:
      POSTGRES_USER: email_user
      POSTGRES_PASSWORD: email_pass
      POSTGRES_DB: email_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  mailpit:
    image: axllent/mailpit
    container_name: email_smtp
    ports:
      - "8025:8025"    # Веб-интерфейс
      - "1025:1025"    # SMTP

  app:
    build: .
    container_name: email_api
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
      - ./tests:/tests
    env_file:
      - .env
    depends_on:
      - db
      - mailpit

volumes:
  pgdata:
