version: '3.9'

services:
  db:
    image: postgres:15
    container_name: email_pg
    restart: always
    environment:
      POSTGRES_USER: email_user
      POSTGRES_PASSWORD: email_pass
      POSTGRES_DB: email_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
